version: "3"
services:

    api:
        image: stevev0189/sven.ai:0.6.7
        ports:
            - "9001:9001"
        environment: 
            - AccessTokens__GitHub=$GITHUBACCESSTOKEN
        command: --urls "http://api"

    frontend:
        image: stevev0189/sven.ai.web:0.6.7
        ports:
            - "5000:5000"

    nginx:
        image: nginx:alpine
        ports:
            - "12111:12111"
        volumes:
            - ./nginx/portfolio.conf.d:/etc/nginx/conf.d