version: "3"
services:

    api:
        image: stevev0189/sven.ai:0.2.14
        ports:
            - "9001:9001"
        environment: 
            - AccessTokens__GitHub=$GITHUBACCESSTOKEN

    frontend:
        image: stevev0189/sven.ai.web:0.2.14
        ports:
            - "5000:5000"
        environment:
            - ApiUrl=$ApiUrl

    nginx:
        image: nginx:alpine
        ports:
            - "12111:12111"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d