version: "3"
services:
    frontend:
        image: stevev0189/sven.ai.web:0.2.5
        ports:
            - "5000:5000"
    nginx:
        image: nginx:alpine
        ports:
            - "12111:12111"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d