name: Build and Publish sven.ai

on: [push]

jobs:

  version-build:
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Git History
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
            versionSpec: '5.2.x'

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.2
        with:
            useConfigFile: true
            configFilePath: 'GitVersion.yml'

  build-frontend:
    runs-on: ubuntu-latest
    needs: version-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build SvenAiWeb Docker Image
        run: docker build -t stevev0189/sven.ai.web:${{ needs.version-build.outputs.version }} SvenAiWeb
      
      - name: Log in to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push the Built Docker Image
        run: docker push stevev0189/sven.ai.web:${{ needs.version-build.outputs.version }}
    
  build-api:
    runs-on: ubuntu-latest
    needs: version-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build SvenAi Docker Image
        run: docker build -t stevev0189/sven.ai.web:${{ needs.version-build.outputs.version }} SvenAi
      
      - name: Log in to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push the Built Docker Image
        run: docker push stevev0189/sven.ai:${{ needs.version-build.outputs.version }}

  update-docker-compose:
    runs-on: ubuntu-latest
    needs:
      - build-api
      - build-frontend
      - version-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Update docker-compose.yml for SvenAiWeb
        run: sed -i -r "s/sven.ai.web:.+/sven.ai.web:${{ needs.version-build.outputs.version }}/g" docker-compose.yml

      - name: Update docker-compose.yml for SvenAi
        run: sed -i -r "s/sven.ai:.+/sven.ai:${{ needs.version-build.outputs.version }}/g" docker-compose.yml

      - name: Add & Commit Updated docker-compose.yml
        uses: EndBug/add-and-commit@v3.0.0
        with:
          author_name: Git CI
          message: Update docker images with latest tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: update-docker-compose
    steps:
      - name: Restart docker-compose on Remote Server
        uses: appleboy/ssh-action@a2f91cbad15a1f1f30ed316d0a9cbccdc33f23d4
        with:
          host: sven.ai
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: sudo ./restart-docker.sh