name: Build and Publish sven.ai.web Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.2
        with:
            versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.2

      - name: Build SvenAiWeb Docker image
        run: docker build SvenAiWeb --tag stevev0189/sven.ai.web:${{ steps.gitversion.outputs.majorMinorPatch }}
      
      - name: Log in to DockerHub Registry
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push the built Docker image
        run: docker push stevev0189/sven.ai.web:${{ steps.gitversion.outputs.majorMinorPatch }}
      
      - name: Read previous docker-compose.yml
        run: cat docker-compose.yml
      
      - name: Update docker-compose.yml
        run: sed -i -r "s/sven.ai.web:.+/sven.ai.web:${{ steps.gitversion.outputs.majorMinorPatch }}/g" docker-compose.yml
      
      - name: Read docker compose file
        run: cat docker-compose.yml
      
      - name: Add & commit updated docker-compose.yml
        uses: EndBug/add-and-commit@v3.0.0
        with:
          author_name: Git CI
          message: Update docker images with latest tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Restart docker-compose on remote server
        uses: appleboy/ssh-action@master
        with:
          host: sven.ai
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: sudo ./restart-docker.sh